- README.md
On recent versions of rustup, it attempts to auto-install clippy, which isn't available for that particular nightly:
```
$ rustup toolchain install nightly-2019-08-05                                                                                                                                                                                                         
info: syncing channel updates for 'nightly-2019-08-05-x86_64-apple-darwin'
info: latest update on 2019-08-05, rust version 1.38.0-nightly (d3f8a0b5d 2019-08-04)
error: component 'clippy' for target 'x86_64-apple-darwin' is unavailable for download for channel nightly-2019-08-05
```
Adding `--force` causes it to skip clippy:
```
$ rustup toolchain install nightly-2019-08-05 --force
info: syncing channel updates for …
```
> README.md: Add --force to rustup install documentation

- src/bin/mir-json-rustc-wrapper.rs
This enables `crux-mir`'s new support for test filtering: `cargo crux-test foo` will run only those tests that have `foo` in the name.  See GaloisInc/mir-verifier#15 for details.
> pass test file to crux-mir via --cargo-test-file

- README.md
- src/analyz/mod.rs
- src/analyz/to_json.rs
- src/analyz/ty_json.rs
- src/bin/cargo-crux-test.rs
- src/bin/mir-json-rustc-wrapper.rs
- src/bin/mir-json.rs
- src/lib.rs
Aside from the usual updates to account for rustc refactoring, this also required a bunch of improvements to constant handling.  See GaloisInc/mir-verifier#23 for more info.
> Update to Rust nightly-2020-03-22

- Cargo.lock
- Cargo.toml
- README.md
- src/bin/wrapper.rs
This renames every binary `foo` to `foo_real`, and adds a wrapper `foo` that sets `$(DY)LD_LIBRARY_PATH` appropriately before invoking `foo_real`.  The library path is determined automatically by invoking `rustc +nightly-2020-03-22 --print sysroot`, so it should come up with the right path regardless of `rustup` install location.
Tested on Linux and macOS
> Add a wrapper that sets the library path

- src/bin/mir-json-rustc-wrapper.rs
This branch changes the test-runner script generated by `cargo crux-test` to invoke `$CRUX_MIR` (if that variable is set) instead of always invoking `crux-mir`.  This makes it easier to use `cargo crux-test` with `crux-mir-comp` - previously, you had to manually symlink `crux-mir` to `crux-mir-comp`, but now you can simply `export CRUX_MIR=crux-mir-comp` instead.
> allow changing crux-mir binary path using CRUX_MIR env var

- doc/rustc.md
- src/bin/mir-json-rustc-wrapper.rs
Fixes https://github.com/GaloisInc/mir-json/issues/43.
> Add `SAW_RUST_LIBRARY_PATH` alias for `CRUX_RUST_LIBRARY_PATH`

- src/analyz/mod.rs
> Mark `AssocFn` items as roots

- Cargo.lock
Update the openssl wrapper crate to get one that understands aarch64 on macOS.
(done with: cargo update --package openssl-src)
This is required to build on macos with Apple Silicon.
> Update the openssl wrapper crate to get one that understands aarch64 on macOS.

- src/analyz/ty_json.rs
The idea is to split the slice into a reference and a separate static allocation for the body the reference points to. This then allows downstream code to treat the references as normal references to memory, which in turn avoids problems in SAW that arise when it goes to try to enforce disjointness.
Requires accompanying changes in Crucible so that crucible-mir can read and process the new output. (These changes are in [crucible #1243](https://github.com/GaloisInc/crucible/pull/1243).)
See [saw-script #2064](https://github.com/GaloisInc/saw-script/issues/2064) for background.
> Rearrange the handling of constant slices.

- README.md
- SCHEMA_CHANGELOG.md
- src/analyz/mod.rs
- src/lib.rs
- src/lib_util.rs
- src/link.rs
- src/schema_ver.rs
We now include a `"version": <N>` entry in the top-level JSON map that gets generated for each MIR JSON file, where `<N>` represents the version of the JSON schema that is used to generate the file. Going forward, any changes to the JSON schema will be accompanied by a corresponding schema version bump. I have also included some logic in `link_crates` to ensure that all of the crates being linked together use the same schema version.
Fixes #45.
> Explicitly version the JSON schema

- README.md
- SCHEMA_CHANGELOG.md
As I mentioned in #75 too late to get wedged in there.
> Minor adjustments to the documentation for the JSON schema version

- .github/ci.sh
- .github/workflows/ci.yml
> Initial CI build

- doc/rustc.md
- src/bin/mir-json-rustc-wrapper.rs
Fixes #67.
I wasn't really sure how to name `MIR_JSON_USE_RUSTC_LIBRARY`, feel free to suggest something better.
> Require `{CRUX,SAW}_RUST_LIBRARY_PATH` or `MIR_JSON_USE_RUSTC_LIBRARY`

- Cargo.toml
- src/bin/cargo_test_common.rs
- src/bin/mir-json-rustc-wrapper.rs
- Add `autobins = false` in `Cargo.toml` to prevent auto-discovery of `cargo_test_common` as binary
- Format string directly in `panic!`
- Remove unused imports
- Unwrap discarded `Result`
There is still a cargo warning about `wrapper.rs` being present in multiple build targets, but there doesn't seem to be a way to disable it, so I'm leaving it like this for now.
> Resolve cargo and rustc warnings

- .github/workflows/ci.yml
- .github/workflows/docker.yml
This repo uses a branch named `master`, not `main`. This fixes incorrect references to `main` in the CI configuration.
> CI: Fix branch name

- src/analyz/mod.rs
- src/analyz/to_json.rs
- src/analyz/ty_json.rs
Replaced the basic_json_impl! and basic_json_enum_impl! macros with explicit ToJson impls. Enum variants and types are now handled directly in code rather than through macro expansion. This avoids silent changes to the JSON schema if variant names shift between rustc versions.
This should resolve:
https://github.com/GaloisInc/mir-json/issues/72
> Remove basic_json_impl! and basic_json_enum_impl! macros

- src/analyz/mod.rs
- src/analyz/ty_json.rs
- src/lib_util.rs
`mir-json` now renders `DefId`s for [lang items](https://doc.rust-lang.org/nightly/unstable-book/language-features/lang-items.html) as `$lang/0::<lang_item_name>` so that we can refer to lang items directly by name. This is useful for wiring in definitions directly into `crucible-mir`, but it has the downside that SAW users will have a more difficult time looking up lang item names in SAW. For instance, one could not simply look up `core::option::Option` anymore; instead, one has to look up `$lang::Option`, which is less intuitive.
To make the lives of SAW users a little easier, this adds an additional `lang_items` field to the MIR JSON output that records each lang item `DefId` along with its original, fully qualified `DefId`. For now, we only record the `DefId`s for ADT definitions, as …
> Record lang items and their original IDs in the JSON output

- doc/rustc.md
This adds a suggestion in the documentation to use `--edition 2021` or later, as `--edition 2015` has been observed to produce undesirably large MIR JSON files.
Fixes https://github.com/GaloisInc/mir-json/issues/94. Supersedes https://github.com/GaloisInc/mir-json/pull/103.
> `doc/rustc.md`: Suggest using `--edition 2021` or later with `{crux,saw}-rustc`

- src/bin/mir-json-translate-libs.rs
Doing so is necessarily to build the `compiler_builtins` crate on ARM64 Linux, as it references the value of `cargo`'s `OUT_DIR` environment variable at build time.
Fixes https://github.com/GaloisInc/mir-json/issues/111.
> `mir-json-translate-libs`: Define `OUT_DIR` when invoking `mir-json`

- src/bin/mir-json-translate-libs.rs
Rust lets you easily run `rustc` for a non-host target by doing `rustup target add` to your toolchain. But for many targets, compilation won't actually work all the way, because `rustc` expects you to have a linker for the target platform installed, which `rustup` does not provide. However, if you are just trying to generate MIR for a certain target, this shouldn't be a requirement.
In `mir-json-translate-libs`, we run `cargo test -Zbuild-std` on a new cargo project with the appropriate target to determine how to build the standard libraries. If we don't have a linker for the given target, it will fail at the end when it tries to link the test binary, even though at that point we will have already collected all the information we need about how to compile the standard libraries. So we …
> `mir-json-translate-libs`: Make it easier to generate MIR for cross-compilation targets

- src/bin/mir-json-translate-libs.rs
This is useful for adding support for additional targets which have target-specific standard library dependencies. For instance, `wasm32-unknown-unknown` depends on `dlmalloc` but most host OS targets do not. So running `mir-json-translate-libs --copy-sources libs --target wasm32-unknown-unknown` after already having run `mir-json-translate-libs --copy-sources libs` won't try to copy libraries other than `dlmalloc` which are already in `libs`.
> `mir-json-translate-libs`: In `--copy-sources` mode, only copy a library if it doesn't already exist

- src/analyz/mod.rs
Previously, `vtable_descriptor_for_cast` only supported casts where the from/to types were references or raw pointers. Besides these two types, it is also possible to have unsized coercions between structs where exactly one of the struct's underlying fields differ and require a reference/pointer cast. This is the sort of cast seen in the example in GaloisInc/crucible#1433.
This adds support for struct-related vtable casts by extending `vtable_descriptor_for_cast` as needed. When the from/to types are structs, we recursively walk over the fields of the structs to find a pair of mismatched field types, which we use to compute the vtable to use in the cast.
Fixes one half of GaloisInc/crucible#1433. (The other half will be on the `crucible-mir` side.)
> `vtable_descriptor_for_cast`: Support vtable casts involving structs

- src/analyz/to_json.rs
This patch equips `from_trait_ref` to handle clauses of the form `where Foo: Bar<Item = Type>`.
Fixes #128.
> Handle `Projection`s in `from_trait_ref`

- libs/crucible/symbolic.rs
Previously, `libs/crucible` used a macro to implement `Symbolic` for a few specific array sizes.  This branch instead uses const generics, so it works for all sizes.
This branch also removes the `T: Copy` bound, which isn't needed when using `array::from_fn` to build the array.
> libs/crucible: use const generics for `impl Symbolic for [T; N]`

- src/analyz/to_json.rs
- src/analyz/ty_json.rs
> Consistently format disambiguators with 8 characters

- src/analyz/mod.rs
- src/analyz/ty_json.rs
See code comments for details. In short, this allows us to manually obtain and call an appropriate drop function for a trait object in situations where rustc doesn't do so for us.
> Expose appropriate drop method in traits and vtables

- libs/crucible/lib.rs
- libs/crucible/method_spec/mod.rs
Adds definitions in `libs/crucible/` for the new functions introduced in GaloisInc/crucible#1469
> add crucible-mir debug helpers

- libs/crucible/cryptol.rs
Adds a new function, which is overriden to declare that a symbol should be kept uninterpreted.
> Add function for declaring uninterpreted functions

- src/analyz/mod.rs
This ought to bring these shims in line with how Rust defines them - see e.g. [`Fn::call`](https://doc.rust-lang.org/std/ops/trait.Fn.html#tymethod.call), which is specified as `extern "rust-call"` (as are its `FnMut` and `FnOnce` siblings).
> analyz: `FnPtrShim`s have `RustCall` ABI

- libs/Patches.md
- libs/core/src/array/mod.rs
Mimics the approach taken in `core::slice::as_array` (see a087518725ff6c352713531c65495943af54e7e1). The normal implementation of `from_ref` does not lend itself well to `crucible-mir`-driven verification, so I intend to define an override for this hook in `crucible`.
> libs: define overridable hook for `core::array::from_ref`

- libs/Patches.md
- libs/crucible/alloc.rs
Instead of using `NonNull::cast` to convert a `NonNull<T>` to a `NonNull<u8>`, use `core::mem::transmute`, to prevent downstream issues in `crucible-mir`.
`crucible-mir` gives special treatment to several casts, including from `*const [T; N]` to `*const T`. In Rust, this is a no-op, because Rust makes no distinction between pointers to arrays and pointers to their first elements. `crucible-mir`, however, uses an explicitly array-shaped representation for pointers to arrays, so when it sees such a cast, it needs to insert an index-0 operation to get the first element of its array and keep its semantics aligned with Rust's. This is unideal, but often innocuous.
It becomes nocuous when trying to allocate space for `[u8; N]`s - e.g., for a `Vec<[u8; N]>`. At this type, …
> crucible: `transmute` pointers in `TypedAllocator` allocation

- libs/Patches.md
- libs/core/src/slice/raw.rs
This is similar to the approach in #147, which allowed hooking `core::array::from_ref`. Truly mimicking that approach would mean working with `core::array::from_mut`, which `slice::from_mut` calls. However, `crucible`'s special array representation makes it impossible to implement an override that would alias `array::from_mut`'s input and output references, and because those references are mutable, that shortcoming would be especially noticeable.
> libs: define overridable hooks for `core::slice::from_{ref,mut}`

- SCHEMA_CHANGELOG.md
- src/analyz/mod.rs
- src/bin/cargo_test_common.rs
- src/lib_util.rs
- src/link.rs
- src/schema_ver.rs
A more general approach would be to keep all
attributes as part of the translation, but
for the moment this is sufficient.
> Add a field to track which of the roots are tests
